### ISSUE TITLE
getRoomList 오류

### ISSUE THREAD

**Issue by tadashi74** [DarkTornado/KakaoTalkBot#3]
문제상황 : Api.getRoomList() 시 답장 가능한 방 목록을 반환하지 않습니다.

![image](https://user-images.githubusercontent.com/88792658/211831856-933751d2-88a1-49a7-b122-dec2f9dc7797.png)

**Comment by DarkTornado** [comment]
[5.0 beta 6](https://github.com/DarkTornado/KakaoTalkBot/releases/tag/v5.0_beta_6)에서 해결하였습니다.
